// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CommonFooter from "./Components/CommonFooter";
import CommonHeaderUnsigned from "./Components/CommonHeaderUnsigned";
import { useRouter } from "next/navigation";
// const router = useRouter();
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CommonHeaderUnsigned />
        {children}
        <CommonFooter />
      </body>
    </html>
  );
}
