// product obj
const products = [
  {
    id: 1,
    prodName: "zara",
    brandName: "Al Karam",
    price: "$95.50",
    status: "Almost Sold Out",
    reviews: "4.1k",
    rating: 5,
    img: "/Homepage/3_sec/1.png",
  },
  {
    id: 2,
    prodName: "Long Dress",
    brandName: "Al Karam",
    price: "$95.50",
    status: "Almost Sold Out",
    reviews: "4.1k",
    rating: 5,
    img: "/Homepage/3_sec/2.png",
  },
  {
    id: 3,
    prodName: "Full Sweater",
    brandName: "Al Karam",
    price: "$95.50",
    status: "Almost Sold Out",
    reviews: "4.1k",
    rating: 5,
    img: "/Homepage/3_sec/3.png",
  },
  {
    id: 4,
    prodName: "White Dress",
    brandName: "Al Karam",
    price: "$95.50",
    status: "Almost Sold Out",
    reviews: "4.1k",
    rating: 5,
    img: "/Homepage/3_sec/4.png",
  },
  {
    id: 5,
    prodName: "Colorful Dress",
    brandName: "Al Karam",
    price: "$95.50",
    status: "Almost Sold Out",
    reviews: "4.1k",
    rating: 5,
    img: "/Homepage/3_sec/5.png",
  },
  {
    id: 6,
    prodName: "White Shirt",
    brandName: "Al Karam",
    price: "$95.50",
    status: "Almost Sold Out",
    reviews: "4.1k",
    rating: 5,
    img: "/Homepage/3_sec/6.png",
  },
  {
    id: 7,
    prodName: "Kurta",
    brandName: "Al Karam",
    price: "$95.50",
    status: "Almost Sold Out",
    reviews: "4.1k",
    rating: 5,
    img: "/Homepage/3_sec/2.png",
  },
];
export default products;
